// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKROvBGOyFx5Do6WcWF5k2wXBjEyF-a1E',
    appId: '1:353808707724:web:64b46d44e1fa8bc0368ba9',
    messagingSenderId: '353808707724',
    projectId: 'fitstation-be102',
    authDomain: 'fitstation-be102.firebaseapp.com',
    storageBucket: 'fitstation-be102.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX1oDt7vUHOwxvZPObmbpnXDZDPqsN7zg',
    appId: '1:353808707724:android:e64ff4767b13a004368ba9',
    messagingSenderId: '353808707724',
    projectId: 'fitstation-be102',
    storageBucket: 'fitstation-be102.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNALvSuynfDWy31dRSwiOeQnTBemSl2Ck',
    appId: '1:353808707724:ios:2d8183d71f8cb28f368ba9',
    messagingSenderId: '353808707724',
    projectId: 'fitstation-be102',
    storageBucket: 'fitstation-be102.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNALvSuynfDWy31dRSwiOeQnTBemSl2Ck',
    appId: '1:353808707724:ios:2d8183d71f8cb28f368ba9',
    messagingSenderId: '353808707724',
    projectId: 'fitstation-be102',
    storageBucket: 'fitstation-be102.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKROvBGOyFx5Do6WcWF5k2wXBjEyF-a1E',
    appId: '1:353808707724:web:bb290226e84bd333368ba9',
    messagingSenderId: '353808707724',
    projectId: 'fitstation-be102',
    authDomain: 'fitstation-be102.firebaseapp.com',
    storageBucket: 'fitstation-be102.firebasestorage.app',
  );
}

// TODO Implement this library.
